import NavBar from '@/components/NavBar/NavBar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body>
      <NavBar />
      <div className="container mx-auto flex justify-center items-center mt-20 flex flex-col min-h-screen">
        <main className="flex-grow">
          {children}
        </main>
      </div>
    </body>
  </html>
  )
}
